### ISSUE TITLE
Feature: add support for node20 runtime

### ISSUE THREAD

**Issue by iamahern** [cardinalby/github-action-ts-run-api#4]
GitHub recently added support for node20 as a target runtime. This is not currently supported by this tool.

**Comment by cardinalby** [comment]
Thanks for the PR. I have also added a deprecation warning for actions using node16 in version 3.0.4

**Comment by iamahern** [comment]
Cheers - thanks for the quick merge and for this library in general. I hadn't seen any deprecation notes yet, but no harm pushing users to upgrade.

**Comment by cardinalby** [comment]
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
